FROM ubuntu:16.04

RUN apt-get update -y && \
    apt-get install -y git curl gnupg-curl openjdk-8-jdk && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

RUN gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4
RUN gpg --finger 5DECF4415E3B8FA4

ADD . /rskj
WORKDIR /rskj

RUN gpg --verify SHA256SUMS.asc
RUN sha256sum --check SHA256SUMS.asc
RUN ./configure.sh
RUN ./gradlew clean build -x test
RUN sha256sum rskj-core/build/libs/*

ENTRYPOINT ["java", "-cp", "./rskj-core/build/libs/rskj-core-1.1.0-SNAPSHOT-all.jar", "co.rsk.Start"]
